site_name: Cédric Belin's Card
site_url: https://docs.belin.io/card
site_author: Cédric Belin - cedric@belin.io
site_description: Business card of Cédric Belin, full stack developer.

docs_dir: ../docs
site_dir: ../www
use_directory_urls: false

edit_uri: edit/main/docs/
repo_name: cedx/card
repo_url: https://github.com/cedx/card

copyright: Copyright &copy; Cédric Belin
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cedx
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/cedxbelin
      name: LinkedIn
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@cedx
      name: Mastodon

extra_css:
  - styles.css

markdown_extensions:
  - admonition
  - pymdownx.superfences

nav:
  - Home: index.md
  - API reference: api/
  - See also:
      - Changelog: changelog.md
      - License: license.md

theme:
  favicon: favicon.ico
  features:
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - search.suggest
  font: false
  logo: logo.png
  name: material
  palette:
    accent: deep purple
    primary: deep purple
